---
# TODO: PHP 7.2 support will be removed soon. This is only being left in here as
# a convenience for legacy PHP 7.2 users.
- name: setup-RedHat | Enable remi repo for PHP 7.2.
  ansible.builtin.set_fact: php_enablerepo="remi,remi-php72"
  when: php_version == "7.2"

- name: setup-RedHat | Enable remi repo for PHP 7.3.
  ansible.builtin.set_fact: php_enablerepo="remi,remi-php73"
  when: php_version == "7.3"

- name: setup-RedHat | Enable remi repo for PHP 7.4.
  ansible.builtin.set_fact: php_enablerepo="remi,remi-php74"
  when: php_version == "7.4"

- name: setup-RedHat | Enable remi repo for PHP 8.0.
  ansible.builtin.set_fact: php_enablerepo="remi,remi-php80"
  when: php_version == "8.0"

# See: https://github.com/ansible/ansible/issues/64852
- name: setup-RedHat | Dnf based setup
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
  block:
    - name: setup-RedHat | Ensure dnf-plugins are installed on CentOS 8+.
      ansible.builtin.yum:
        name: dnf-plugins-core
        state: present

    - name: setup-RedHat | Enable DNF module for CentOS 8+.
      ansible.builtin.shell: |
        dnf config-manager --set-enabled powertools
        dnf module enable -y php:remi-{{ php_version }}
      args:
        warn: false
      register: dnf_module_enable
      changed_when: "'Nothing to do' not in dnf_module_enable.stdout"
