---
#
# Ansible managed
#

name: "Dependabot Merge"

on:
  pull_request:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
<<<<<<< HEAD
  dependabot_merge:
    runs-on: "ubuntu-latest"
=======
  build:
    runs-on: "ubuntu-22.04"
>>>>>>> fc2bbee8a9467a199ca661c012498296c81a8b5d
    steps:
      - uses: "actions/checkout@master"
      - name: Dependabot Auto Merge Action
        uses: buluma/dependabot-auto-merge-action@v2.0.2
